added confirmation before deleting submissions, users and problems
acm-mu/abacus pull request #222
Opened 2021-10-08 18:40 UTC by MrKevinOConnell

# Description

- confirmation window shows before users, submissions and problems are deleted
- upon the deletion occurring successfully a toast container shows
- I want to add a follow up issue for someone else to do for displaying a error message

Fixes #72 

## Type of change

- [x] 💡 New feature

# How Has This Been Tested?

- select a user on the table, click delete selected

<img width="100" alt="Screen Shot 2021-10-08 at 1 36 02 PM" src="https://user-images.githubusercontent.com/17347501/136609311-3129f566-9837-4b26-abb1-82b517c1f43d.png">

- select ok, the user should be deleted, and a message should be displayed confirming the deletion occurred

<img width="100" alt="Screen Shot 2021-10-08 at 1 39 15 PM" src="https://user-images.githubusercontent.com/17347501/136609664-a0998720-d3ad-459e-9a67-5f90e23c471e.png">

- [x] Tested individually.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] My changes do not break any features.

2021-10-18 20:56 UTC, MrKevinOConnell commented
@Jl5her whenever the server returns a call we prompt toast by sending a toast.success or toast.error depending on the result (which gets sent to the container, makes it a lot easier to manage notifications

2021-11-18 16:16 UTC, a1g3 requested changes
Make sure you've also implemented the changes Jack P. requested.

2021-11-18 16:16 UTC, a1g3 commented on frontend/src/pages/admin/submissions/Submissions.tsx
> +        const id = submissionsToDelete.join()
Why do the submissions have to be joined to form the `id`?

2021-11-18 16:16 UTC, a1g3 commented on frontend/src/pages/admin/users/Users.tsx
> +        const id = usersToDelete.join()
See my previous comment.

2021-11-22 01:33 UTC, JForden submitted a review, later dismissed

2021-11-22 01:34 UTC, MrKevinOConnell commented on frontend/src/pages/admin/submissions/Submissions.tsx
> +        const id = submissionsToDelete.join()
not sure, that was something that jack made

2021-12-06 07:36 UTC, merged