Ko 229
acm-mu/abacus pull request #230
Opened 2021-11-15 18:56 UTC by MrKevinOConnell

# Description

- when retrieving a page from the DB, there is now a check to see how many pages are in the table, and if the given page does not exist.

Fixes #229 

## Type of change

- [x] 💡 New feature

  
# How Has This Been Tested?

- upon loading the users table the correct number of pages should show (have 5 users per page at the moment for testing reasons 

- [x] Tested individually.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] My changes do not break any features.

2021-11-18 16:06 UTC, a1g3 requested changes
What is the relation between this PR and PR #228?

2021-11-18 16:06 UTC, a1g3 commented on frontend/src/pages/admin/Clarifications.tsx
> +  // <ClarificationModal trigger={<Button content="Create Clarification" />} callback={loadClarifications} />
Can remove this if its not needed.

2021-11-18 18:04 UTC, MrKevinOConnell commented on frontend/src/pages/admin/Clarification.tsx
> +    if (response.ok) {
After a couple calls are made to update the page the component stops being mounted, so I just removed it (not sure when actions would occur on a non used component anyways)

2021-11-18 18:05 UTC, MrKevinOConnell commented on backend/src/api/auth/getTableSize.ts
> +    const pages = tableSize ? tableSize / 5 : 0
tablesize returns the total number of items in a table. For the purpose of showing the pagination functionality I set each page to 5 items, what that does is divide by 5 to get the number of pages

2021-11-18 18:06 UTC, MrKevinOConnell commented on backend/src/services/db/dynamo.ts
> +            params.ExpressionAttributeNames = Object.assign({}, ...entries.map((x) => ({ [`#${x[0]}`]: x[0] })))
lmao, yea that's jack

2021-11-18 18:08 UTC, MrKevinOConnell commented on backend/src/api/auth/getTableSize.ts
> +export const getTableSize = async (req: Request, res: Response) => {
this makes it so every time we make a call to get a page, we can
1. make sure the page is still valid
2. update the number of pages for future calls

what do you suggest is a better way of doing this?

2021-11-18 18:09 UTC, MrKevinOConnell commented on frontend/Dockerfile
> +FROM node:16
Yea, I figured this out here https://github.com/acm-mu/abacus/pull/228, just reverted to 16

2021-11-18 18:35 UTC, MrKevinOConnell commented on backend/src/services/db/mongo.ts
> +  scan(TableName: string, query?: ScanOptions, page?: number): Promise<Item[]> {
to be honest, I tried implementing it into args of ScanOptions but had some trouble due to the key being checked into mongo as part of the scan call (not sure how to delete the record from the property.)

2021-12-06 08:19 UTC, MrKevinOConnell commented on frontend/src/pages/admin/Clarifications.tsx
> +      if (tableSize < numberOfPages) {
this is if the call comes back and tablesize is higher than numberpages (due to new clarifications being made

2021-12-06 17:33 UTC, MrKevinOConnell commented on backend/src/services/db/dynamo.ts
> +  count(TableName: string, query: ScanOptions): Promise<number> {
it doesn't but we need a function for each table

2021-12-06 17:36 UTC, MrKevinOConnell commented on backend/src/api/submissions/getSubmissions.ts
> +    if (submissions !== []) {
I was getting errors in the case of there being no users in a table, so i added a couple checks

2021-12-06 17:38 UTC, MrKevinOConnell commented on frontend/src/pages/admin/Clarifications.tsx
> +      if (tableSize < numberOfPages) {
> What is the relation between this PR and PR #228?

this goes off of it, just adds the implementation of pages

2021-12-07 21:59 UTC, merged

2021-12-07 22:58 UTC, Jl5her commented on frontend/src/pages/admin/Clarification.tsx
> +    if (response.ok) {
If the user clicks away from the page before the server responds, this check will prevent react from updating the page that is no longer mounted.