Ko 247
acm-mu/abacus pull request #248
Opened 2022-03-25 22:04 UTC by MrKevinOConnell

# Description

Fixes #247 

## Type of change

- [x] 💡 New feature

# How Has This Been Tested?

- tested with a java submission that was correct
- with a java submission that isn't correct
- tested with a java submission that doesn't compile
- [x] Tested individually.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] My changes do not break any features.

2022-03-27 19:25 UTC, a1g3 requested changes

2022-03-27 19:25 UTC, a1g3 commented on backend/src/api/submissions/postSubmissions.ts
> +          console.log('res', res.data)
You can probably remove the console.log statements.

2022-03-27 19:25 UTC, a1g3 commented on backend/src/api/submissions/postSubmissions.ts
> +          if ((res.data.run.output.trim() as string) == (test.out.trim() as string) || res.data.run.code !== 0) {
For this, wouldn't we want to reject the submission of the process returns a non-zero code?

2022-03-27 19:25 UTC, a1g3 commented on frontend/src/pages/blue/Submit.tsx
> +    formData.set('language', language.value)
Was this the wrong thing from before?

2022-03-27 19:58 UTC, MrKevinOConnell commented on backend/src/api/submissions/postSubmissions.ts
> +          console.log('res', res.data)
👍🏻

2022-03-27 19:59 UTC, MrKevinOConnell commented on backend/src/api/submissions/postSubmissions.ts
> +          if ((res.data.run.output.trim() as string) == (test.out.trim() as string) || res.data.run.code !== 0) {
yea your right, good call

2022-03-28 15:36 UTC, a1g3 approved these changes

2022-03-28 15:36 UTC, merged