Replace react-helmet dependency with custom usePageTitle
acm-mu/abacus pull request #289
Opened 2023-10-08 21:31 UTC by Jl5her

# Description

To reduce dependencies and since react-helmet is only used to adjust the document title. Something that could be done easily without a dependency. This PR removes the need for the dependency by replacing all uses with a custom `usePageTitle` hook.

## Type of change

- [x] 💡 New feature

- [x] 🧹 Code Cleanup

  
# How Has This Been Tested?

Ran the website locally and navigated to several pages (including dynamic and static page titles) to see the title changing.

- [x] Tested individually.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] My changes do not break any features.

2023-10-09 21:38 UTC, Jl5her commented on frontend/public/index.html
This is a temporary fix since the mark down viewer detects dark mode, but the rest of abacus does not

2023-10-11 13:46 UTC, brad-cooley commented on frontend/src/components/Footer.tsx
>      Developed with <RickRoll trigger={<a href="#">💙</a>} /> by members of{' '}
Forgot we did this, lol

2023-10-11 14:28 UTC, brad-cooley requested changes

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/admin/users/UploadUsers.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/admin/users/Users.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/Home.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/Home.tsx
> +import React, {useState} from 'react'
```suggestion
import React, { useState } from 'react'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/Problem.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/Problems.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/Rules.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/Rules.tsx
> +import React, {useContext} from 'react'
```suggestion
import React, { useContext } from 'react'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/Standings.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/Submission.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/Submissions.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/Submit.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/practice/Problem.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/practice/ProblemOrSubmission.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/practice/Problems.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/practice/Submit.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/practice/index.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/blue/practice/index.tsx
> +import React, {useContext} from 'react'
```suggestion
import React, { useContext } from 'react'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/eagle/Home.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/eagle/Problem.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/gold/Home.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/gold/Home.tsx
> +import React, {useState} from 'react'
```suggestion
import React, { useState } from 'react'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/gold/Problem.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/gold/Problems.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/gold/Rules.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/gold/Rules.tsx
> +import React, {useContext} from 'react'
```suggestion
import React, { useContext } from 'react'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/gold/Standings.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/gold/Submission.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/gold/Submissions.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/gold/Submit.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/judge/Home.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/judge/Problem.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/judge/Problems.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/judge/Submission.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/judge/Submissions.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/judge/Users.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/proctor/Home.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/proctor/Problems.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/proctor/Submission.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-11 14:28 UTC, brad-cooley commented on frontend/src/pages/proctor/Submissions.tsx
> +import {usePageTitle} from 'hooks'
```suggestion
import { usePageTitle } from 'hooks'
```

2023-10-12 15:08 UTC, brad-cooley approved these changes

2023-10-19 12:40 UTC, merged